### ISSUE TITLE
Yank and paste

### ISSUE THREAD

**Issue by DavidFSol** [wolandark/wim#1]
Hey Woland! First of all THANK YOU for this! It's really the best vimrc I've found. And I've been searching for ages.

I have a little issue. Normally I use "#yy" or "#dd" and "p" to cut or copy and paste "#" amount of lines. This does not seem to work in your file, so you probably remaped those keys. How can I set this back to the original way? And where in the vimrc do you modify this behavior?

Thanks again,
David

**Comment by wolandark** [comment]
Hello David and thank you for your feedback and interest and apologies for the late reply.
I have not by any means modified the behavior of yy dd p. (cause why would anyone?)
Please provide more information about your terminal, keyboard layout, language etc...
It may be that the encoding option at the top of the config file is causing that or the language specified under spell check section.
Please comment them out one by one and check to see if that solves your problem.
You may also want to comment or modify the <code>set clipboard=unnamedplus</code> to <code>set clipboard=unnamed</code> if you're using OSX.

For global shared clipboard with a browser however you would use c p in visual mode to yank and c v to paste, again in visual mode. This requires the xsel package to work which I added to the dependencies.
