### ISSUE TITLE
cursor shape

### ISSUE THREAD

**Issue by aminkhani** [wolandark/wim#10]
Hello. Thanks for best Wim config.
My terminal default cursor shape is I-Beam and also in vim editor is I-Beam too but when I for example open terminal in vim (space+t) and then I close it, my cursor shape change to block shape and also affect to my terminal too, Is is bug??
Regards.

**Comment by wolandark** [comment]
Use `echo -e -n "\x1b[\x36 q" `  in your `~/.bashrc` to achieve an ibeam cursor instead of your terminal's internal settings. I just tested with xfce terminal and xterm and didn't see any issues.
