### ISSUE TITLE
Cursor Change Delay

### ISSUE THREAD

**Issue by Tainted-Fool** [wolandark/wim#5]
Hello!

I am loving this vim configuration! Keep up the good work!

Sadly, I am experiencing one issue. I prefer the cursor a certain way so I went ahead and changed line 152 and 153
from

```
let &t_SI = "\<Esc>]50;CursorShape=1\x7"
let &t_EI = "\<Esc>]50;CursorShape=0\x7"
```

to

```
let &t_SI = "\e[3 q" 
let &t_EI = "\e[1 q" 
```

This sets the cursor style to blinking block and blinking underline when switching between modes. After changing the style, I notice a cursor change delay when you switch modes i.e. switching between normal, insert, and visual mode.

My guess is that there might be something wrong in the config; something is causing the delay. I ran a test using a different vim config and there was no issues. My old vimrc also did not experience this issue.

Here is a demonstration of what I mean:
![wim_bug](https://user-images.githubusercontent.com/19850526/177656995-821b8b67-edec-4abb-83ba-a7487b0ef99b.gif)

+ open vim using wim config - only changed the cursor settings
+ change between normal and insert mode - notice delay
+ open vim using a different config with the `-u` flag - config only has cursor settings
+ change between normal and insert mode - notice NO delay

What might be the issue here? Any help would be greatly appreciated as I use different cursor styles to distinguish what vim mode I am using.

**Comment by ArianaAsl** [comment]
Try the` <nowait>`option and `set timeoutlen=300`

**Comment by wolandark** [comment]
@Tainted-Fool Thank you for the kind words. I personally dont see the delay you're talking about. Play with the timeoutlen as suggested by @ArianaAsl and see if that fixes it for you. Typically lightline statusline is not the fastest thing when it comes to changing modes. I have my timeoutlen set to 300 to make it tolerable which will be included in Wim-2.2. So doing the same will probably make the cursor changes faster too. cheers.

**Comment by Tainted-Fool** [comment]
That worked guys thanks a lot!

**Comment by wolandark** [comment]
glad it helped and keep in mind that if you lower the timeout to ridiculous values like 100, using macros and normal mode commands will become a race. cheers.
