### ISSUE TITLE
Vim keeps jumping into stdio.h

### ISSUE THREAD

**Issue by jkrause1** [wolandark/wim#6]
I used this environment with coc-clangd installed, to write some small C programs with it. No further additions to it has been made.

After saving my main.c with the arguments for the function `dprintf` used in the wrong order, vim keeps jumping into the stdio.h, where dprintf is defined, along with the error message, and doesn't let me get back to my .c-file.

**Comment by wolandark** [comment]
Hi. try disabling syntastic. It would also be helpful to know the error msg and your vim version. cheers

**Comment by wolandark** [comment]
Im going to close this since there is no reply

**Comment by jkrause1** [comment]
This is actually still an issue.

I don't know how to disable syntastic, a quick google search brought up nothing, and an issue on their repository even suggests they don't even have such a basic feature as just disabling it. That alone was enough to cause a meltdown for me today ...

Take the following code example

```
#include<iostream>
#include<functional>

class Test{
    public:
        Test(int value);
        int TestFunction(int a, int b);
    private:
        int c;
};

Test::Test(int value){
    this->c = value;
}

int Test::TestFunction(int a, int b){
    int result = a + b + this->c;
    return result;
}

int main(int argc, char** argv){
    Test stuff(5);

    int result = stuff.TestFunction(2, 4);
    std::cout << result << std::endl;

    std::function<int(int,int)> f = std::bind(&Test::TestFunction, stuff);
    result = f(1, 2);
    std::cout << result << std::endl;

    return EXIT_SUCCESS;
}
```

Save it somewhere, and have coc-clangd installed for c++ stuff.

Now, open that file with wim and it will keep jumping into the functional library, 'cause it suspects the error in there. From this point on, it is not possible anymore to open the original file, as it will _always_ jump into the wrong place.
